#!/bin/sh
#
# @name Gazebo X500 with Lidar and Camera
#
# @type Quadrotor
# @class Copter
#

. ${R}etc/init.d/rc.mc_defaults

# Simulator configuration
PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_lidar_camera}

# Enable Gazebo simulation
param set-default SIM_GZ_EN 1

# CRITICAL: Enable simulated sensors including magnetometer
param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 1
param set-default SENS_EN_ARSPDSIM 0

# EKF2 magnetometer configuration
param set-default EKF2_MAG_TYPE 0       # Automatic magnetometer selection
param set-default EKF2_GPS_DELAY 0      # No GPS delay for simulation

# Vehicle configuration
param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

# Rotor configuration (X500 geometry)
param set-default CA_ROTOR0_PX 0.13
param set-default CA_ROTOR0_PY 0.22
param set-default CA_ROTOR0_KM 0.05

param set-default CA_ROTOR1_PX -0.13
param set-default CA_ROTOR1_PY -0.20
param set-default CA_ROTOR1_KM 0.05

param set-default CA_ROTOR2_PX 0.13
param set-default CA_ROTOR2_PY -0.22
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.13
param set-default CA_ROTOR3_PY 0.20
param set-default CA_ROTOR3_KM -0.05

# Gazebo motor control functions
param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104